apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "safemirror.fullname" . }}-worker
  labels:
    {{- include "safemirror.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "safemirror.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "safemirror.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "safemirror.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.worker.image.repository }}:{{ include "safemirror.imageTag" . }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            - celery
            - -A
            - enterprise.workers
            - worker
            - -l
            - info
            - --concurrency={{ .Values.worker.concurrency }}
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "safemirror.secretName" . }}
                  key: {{ .Values.secrets.databasePasswordKey }}
            - name: DATABASE_URL
              value: {{ include "safemirror.databaseUrl" . | quote }}
            - name: REDIS_URL
              value: {{ include "safemirror.redisUrl" . | quote }}
            - name: CELERY_BROKER_URL
              value: {{ include "safemirror.redisUrl" . | quote }}
            - name: CELERY_RESULT_BACKEND
              value: {{ include "safemirror.redisUrl" . | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "safemirror.secretName" . }}
                  key: {{ .Values.secrets.secretKeyKey }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
